baseURL = "https://Ama0124.github.io/"
locale = "zh-TW"
title = "My blog"
theme = "reimu"

[outputs]
home = ["Algolia", "HTML", "RSS"]

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[taxonomies]
  tag = "tags"
  category = "categories"

[markup.goldmark.renderer]
  unsafe = true

[[menu.main]]
  name = "首頁"
  url = "/"
  weight = 1

[[menu.main]]
  name = "文章"
  url = "/archives/"
  weight = 2

[[menu.main]]
  name = "關於"
  url = "/about/"
  weight = 3

[[menu.main]]
  name = "好友"
  url = "/friend/"
  weight = 4

summaryLength = 0
preserveTaxonomyNames = true