baseURL = "https://Ama0124.github.io/"
locale = "zh-TW"
title = "My blog"
theme = "reimu"

[outputs]
home = ["Algolia", "HTML", "RSS"]

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[taxonomies]
  tag = "tags"
  category = "categories"

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
guessSyntax = true
noClasses = false

[markup.goldmark.extensions.passthrough]
enable = true
delimiters.block = [["\\[", "\\]"], ["$$", "$$"]]
delimiters.inline = [["\\(", "\\)"], ["$", "$"]]

summaryLength = 0
preserveTaxonomyNames = true