baseURL = 'https://Ama0124.github.io/'
locale = 'zh-TW'
title = 'ういういだいすき'
theme = 'reimu'

[outputs]
home = ["Algolia", "HTML", "RSS"]

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[taxonomies]
  tag = "tags"
  category = "categories"

[markup.goldmark.renderer]
  unsafe = true

summaryLength = 0
preserveTaxonomyNames = true